<!-- @author Kyles Light -->
<!-- @email kuilin@yangqianguan.com -->
<!-- @date 2018-03-28 15:20:38.000 -->
<!-- @desc generated by yqg-cli@0.0.18 -->

<template>
    <div class="yqg-code-textarea">
        <codemirror ref="cm" :value="value" :options="CodeMirrorOptions" v-on="$listeners" />
    </div>
</template>

<script type="text/babel">

    import {codemirror} from 'vue-codemirror';

    import 'codemirror/mode/javascript/javascript';
    import 'codemirror/mode/sql/sql';
    import 'codemirror/lib/codemirror.css';
    import 'codemirror/theme/neo.css';
    import 'codemirror/addon/hint/show-hint.css';

    import 'codemirror/addon/edit/closebrackets';
    import 'codemirror/addon/edit/closetag';
    import 'codemirror/addon/edit/matchbrackets';
    import 'codemirror/addon/edit/matchtags';
    import 'codemirror/addon/hint/show-hint';
    import 'codemirror/addon/hint/sql-hint';

    const CodeMirrorOptions = {
        // Configuration
        indentUnit: 4,
        smartIndent: false, // TODO by panezhang use JSON-LD mode and enable smartIndent
        tabSize: 4,
        lineWrapping: true,

        // Addon Configuration
        autoCloseBrackets: true,
        autoCloseTags: true,
        matchBrackets: true,
        matchTags: true,

        extraKeys: {
            'Tab': cm => {
                if (cm.somethingSelected()) {
                    cm.indentSelection('add');
                    return;
                }

                if (cm.getOption('indentWithTabs')) {
                    cm.replaceSelection('\t', 'end', '+input');
                } else {
                    cm.execCommand('insertSoftTab');
                }
            },

            'Shift-Tab': cm => {
                cm.indentSelection('subtract');
            }

            // TODO by panezhang reformat
            // 'Alt-Cmd-L': () => {
            //
            // }
        }
    };

    export default {
        name: 'YqgCodeTextarea',

        components: {
            codemirror
        },

        props: {
            value: {
                type: String,
                required: true
            },

            mode: {
                type: String,
                default: 'text/javascript'
            },

            options: {
                type: Object,
                default: () => ({})
            }
        },

        computed: {
            CodeMirrorOptions() {
                const {options, mode} = this;
                return {
                    ...CodeMirrorOptions,
                    mode,
                    ...options
                };
            },

            codeMirror() {
                return this.$refs.cm.codemirror;
            }
        },

        mounted() {
            if (this.CodeMirrorOptions.enableAutocomplete) {
                this.codeMirror.on('change', (editor, {origin, text}) => {
                    if (origin === '+input' && text.length === 1 && text[0].trim()) {
                        editor.showHint({
                            completeSingle: false
                        });
                    }
                });
            }
        }
    };

</script>

<style lang="scss" rel="stylesheet/scss" src="./index.scss"></style>
